Dependency testen von Plot Channel, Plot Measuretype

Logger: stdout und file...

DONE: C:\Projekte\ETH-Fir\pymeas2019_noise\compact_measurements\20000101_01-20210310a\DA_DIRECT_+10V\result_INTEGRAL.png
DONE:    Warum "Noise Demo Title"?

DONE: Output reloadable in excel sheet



2021-02-28 18:51:23,972 - logger - Thread-9 - ERROR - Unable to allocate 64.0 MiB for an array with shape (8388862,) and data type float64
Traceback (most recent call last):
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_measurement_stream.py", line 94, in worker
    rc = self.out.push(array_in)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 379, in push
    calculation_stage = self.out.push(None)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 215, in push
    return self.out.push(None)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 116, in push
    return self.out.push(None)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 215, in push
    return self.out.push(None)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 116, in push
    return self.out.push(None)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 215, in push
    return self.out.push(None)
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 118, in push
    array_decimate = self.decimate(self.array[: self.pushcalulator_next.previous_fir_samples_input])
  File "C:\Projekte\ETH-Fir\pymeas2019_noise\pymeas\program_fir.py", line 147, in decimate
    array_decimated = CORRECTION_FACTOR * scipy.signal.decimate(array_decimate, DECIMATE_FACTOR, ftype="iir", zero_phase=True)
  File "C:\Users\maerki\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\signal\signaltools.py", line 4277, in decimate
    y = filtfilt(b, a, x, axis=axis)
  File "C:\Users\maerki\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\signal\signaltools.py", line 3913, in filtfilt
    (y, zf) = lfilter(b, a, axis_reverse(y, axis=axis), axis=axis, zi=zi * y0)
  File "C:\Users\maerki\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\signal\signaltools.py", line 1909, in lfilter
    return sigtools._linear_filter(b, a, x, axis, zi)
MemoryError: Unable to allocate 64.0 MiB for an array with shape (8388862,) and data type float64
2

  File "C:\Users\maerki\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

C:\\Program Files (x86)\\Pico Technology\\PicoScope6\\ps5000a.dll
6.14.10.4759
